directories:
  "app":
    IrresponsibleModule:
      enabled: false
  "app/helpers":
    FeatureEnvy:
      enabled: false
  "config":
    TooManyStatements:
      enabled: false
    IrresponsibleModule:
      enabled: false
  "spec":
    UtilityFunction:
      enabled: false

detectors:
  Attribute:
    enabled: false
  TooManyStatements:
    max_statements: 10
  IrresponsibleModule:
    enabled: false
  FeatureEnvy:
    exclude:
      - "Deposit#initialize"
  UncommunicativeVariableName:
    exclude:
      - "DepositsController"
  UtilityFunction:
    exclude:
      - "Sinatra::ViewsHelper#form_class"


