directories:
  "app":
    IrresponsibleModule:
      enabled: false
  "config":
    IrresponsibleModule:
      enabled: false
  "spec":
    UtilityFunction:
      enabled: false

detectors:
  Attribute:
    enabled: false
  TooManyStatements:
    max_statements: 10