Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: false
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
Style/FormatStringToken:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: true
Metrics/MethodLength:
  Exclude:
    - config/**/*
    - app/models/concerns/deposit/attributes.rb
Metrics/AbcSize:
  Exclude:
    - config/**/*
Layout/LineLength:
  Exclude:
    - spec/**/*
Metrics/BlockLength:
  Exclude:
    - spec/**/*
Style/RescueModifier:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
